name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - v*

env:
  CARGO_INCREMENTAL: 0
  RUST_CACHE_VERSION: v1
  PROJ_NAME: tek-utils

jobs:
  release_linux:
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghimage: ubuntu-24.04
            os: linux
            arch: x86_64
            target: x86_64-unknown-linux-gnu

    permissions:
      contents: write

    runs-on: ${{ matrix.ghimage }}

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - run: |
          # depName=rustfs/cli
          RUSTFS_CLI_VERSION="v0.1.15"
          RUSTFS_CLI_TAR_NAME="rustfs-cli-linux-${{ matrix.rustfscliarch }}-$RUSTFS_CLI_VERSION.tar.gz"
          wget "https://github.com/rustfs/cli/releases/download/$RUSTFS_CLI_VERSION/$RUSTFS_CLI_TAR_NAME"
          tar xf "$RUSTFS_CLI_TAR_NAME"
          rm "$RUSTFS_CLI_TAR_NAME"
          sudo mv rc /bin/

          rc alias set yr32srv https://rustfs-s3.yr32.net tek-utils-ci "${{ secrets.YR32SRV_TEK_UTILS_CI_SECRET }}"
          rc cp yr32srv/visa/ni-ubuntu2404-drivers-stream.deb ./ni-ubuntu2404-drivers-stream.deb
          sudo apt install ./ni-ubuntu2404-drivers-stream.deb
          sudo apt search visa

      - name: Install cargo license
        run: |
          cargo install cargo-license

      - uses: Swatinem/rust-cache@v2.9.1
        with:
          prefix-key: ${{ env.RUST_CACHE_VERSION }}-rust

      - name: Build
        env:
          TARGET: ${{ matrix.target }}
        run: |
          cargo build --release --target $TARGET

      - name: Create CREDITS file
        env:
          TARGET: ${{ matrix.target }}
        run: |
          cargo license \
            --authors \
            --do-not-bundle \
            --avoid-dev-deps \
            --filter-platform $TARGET \
              > CREDITS

      - name: Make release file
        env:
          TARGET: ${{ matrix.target }}
        run: |
          DIR_NAME="${{ env.PROJ_NAME }}-${{ matrix.os }}-${{ matrix.arch }}-${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('master-{0}', github.sha) }}"
          mkdir "$DIR_NAME"
          cp ./target/$TARGET/release/tek-data "$DIR_NAME/"
          cp ./target/$TARGET/release/tek-hardcopy "$DIR_NAME/"
          cp ./LICENSE "$DIR_NAME/"
          cp ./CREDITS "$DIR_NAME/"
          cp ./README.md "$DIR_NAME/"
          tar cvf "$DIR_NAME.tar.gz" "$DIR_NAME/"

      - name: pre-release
        uses: softprops/action-gh-release@v3.0.0
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          tag_name: master-${{ github.sha }}
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            *.tar.gz

      - name: tagged-release
        uses: softprops/action-gh-release@v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            *.tar.gz


  clippy_and_test:
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghimage: ubuntu-24.04
            mcarch: amd64

    permissions:
      checks: write

    runs-on: ${{ matrix.ghimage }}

    steps:
      - uses: actions/checkout@v6.0.2

      - run: |
          # depName=rustfs/cli
          RUSTFS_CLI_VERSION="v0.1.15"
          RUSTFS_CLI_TAR_NAME="rustfs-cli-linux-${{ matrix.rustfscliarch }}-$RUSTFS_CLI_VERSION.tar.gz"
          wget "https://github.com/rustfs/cli/releases/download/$RUSTFS_CLI_VERSION/$RUSTFS_CLI_TAR_NAME"
          tar xf "$RUSTFS_CLI_TAR_NAME"
          rm "$RUSTFS_CLI_TAR_NAME"
          sudo mv rc /bin/

          rc alias set yr32srv https://rustfs-s3.yr32.net tek-utils-ci "${{ secrets.YR32SRV_TEK_UTILS_CI_SECRET }}"
          rc cp yr32srv/visa/ni-ubuntu2404-drivers-stream.deb ./ni-ubuntu2404-drivers-stream.deb
          sudo apt install ./ni-ubuntu2404-drivers-stream.deb
          sudo apt search visa

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - name: install clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.9.1
        with:
          prefix-key: ${{ env.RUST_CACHE_VERSION }}-rust

      - name: clippy check
        uses: yanorei32/action-clippy@50412b135153ebee7d4b8a5b868c4defdc663683
        with:
          reporter: github-check

      - name: unit test
        run: |
          cargo test --no-run --locked
          cargo test

      - name: release build
        run: cargo build --release
